#!/usr/bin/env node

/**
 * @param {import("@nan0web/log")} console
 */
export async function run(console) {
	console.clear()
	console.success("Sitemap Generation Demo")

	const { nano2xml, Case } = await import("../src/index.js")

	const sitemapData = [
		{
			$version: '1.0',
			$encoding: 'UTF-8',
			'?xml': true
		},
		{
			$type: 'text/xsl',
			$href: '//yaro.page/test.xsl',
			'?xml-stylesheet': true
		},
		{
			$xmlns: 'http://www.sitemaps.org/schemas/sitemap/0.9',
			sitemapindex: [
				{
					sitemap: [
						{ loc: 'http://yaro.page/post-sitemap.xml' },
						{ lastmod: '2024-12-28T10:50:59+00:00' }
					]
				},
				{
					sitemap: [
						{ loc: 'http://yaro.page/page-sitemap.xml' },
						{ lastmod: '2024-12-28T10:50:59+00:00' }
					]
				}
			]
		},
		{ '#comment': 'Generated by @nan0web/xml' }
	]

	const xml = nano2xml(sitemapData, {
		indent: '\t',
		newLine: '\n',
		defaultTags: { $attrCase: Case.KEBAB }
	})

	console.info("Generated Sitemap:\n")
	console.info(xml)

	console.success("\nSitemap generation demo complete! 🗺️")
}